### ISSUE TITLE
Having a header or other content that scrolls with the grid

### ISSUE THREAD

**Issue by akvus** [savvasdalkitsis/lazy-staggered-grid#3]
Nesting LazyColumns is not supported, therefore Is there an out-of-a-box solution to have some content on top and/or bottom of the grid that would scroll with it, but take the full width of the screen not depending on the number of the column?

**Comment by savvasdalkitsis** [comment]
This is the big drawback with my approach. There is no way to provide spannable content.

I needed headers for my usecase in https://github.com/savvasdalkitsis/uhuruphotos-android/ too so I ended up not using my implementation here. My dummy staggered grid implementation there might be of interest to you https://github.com/savvasdalkitsis/uhuruphotos-android/blob/main/feature/collage/view/api/src/main/kotlin/com/savvasdalkitsis/uhuruphotos/feature/collage/view/api/ui/StaggeredCollage.kt

**Comment by savvasdalkitsis** [comment]
(the problem there is that only full rows are being recycled, not individual entries, which leads to potential performance issues and issues with item animations as only rows can be animated).

On the plus side, the latest compose beta has added commits for an initial official implementation of lazy staggered grid (marked internal only for now so can't be used) so we can expect it soon-ish hopefully
